services:
  - type: web
    name: front-office
    env: node
    plan: starter
    buildCommand: cd front-office && npm install && npm run build
    startCommand: cd front-office && npm run preview
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
