services:
  - type: static
    name: front-office
    plan: starter
    buildCommand: cd front-office && npm install && npm run build
    publishPath: front-office/dist
    branch: main
    envVars:
      - key: NODE_ENV
        value: production
